name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'EBAC-QE/golden-movie-studio'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Start the server
      run: npm start &
      env:
        NODE_ENV: test

    - name: Wait for server to be ready
      run: sleep 15

    - name: Run Cypress tests
      run: npx cypress run
