name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Cypress repository
      uses: actions/checkout@v2

    - name: Checkout Golden Movie Studio repository
      run: git clone https://github.com/EBAC-QE/golden-movie-studio.git golden-movie-studio

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies for Golden Movie Studio
      run: |
        cd golden-movie-studio
        npm install

    - name: Start the Golden Movie Studio server
      run: |
        cd golden-movie-studio
        npm start &
      env:
        NODE_ENV: test

    - name: Wait for server to be ready
      run: |
        echo "Waiting for the server to be ready..."
        sleep 60
        echo "Continuing after waiting for 60 seconds."

    - name: Check server health
      run: |
        until curl -sSf http://127.0.0.1:8080 > /dev/null; do
          echo "Waiting for the server to be up..."
          sleep 5
        done
        echo "Server is up and running."

    - name: Install Cypress dependencies
      run: npm install

    - name: Run Cypress tests
      run: |
        echo "Running Cypress tests..."
        npx cypress run
