name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Cypress repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Cypress dependencies
      run: npm install

    - name: Run Cypress tests
      run: |
        echo "Running Cypress tests..."
        CYPRESS_BASE_URL=https://golden-movie-studio.vercel.app npm run cypress:run
